### ISSUE TITLE
是否考虑把获取到的文字、图片直接转发到企业微信应用程序上。

### ISSUE THREAD

**Issue by luolovehk** [nfe-w/weibo_dynamic_push#1]
RT

**Comment by nfe-w** [comment]
目前是有这个功能的
![QQ20210913-152121](https://user-images.githubusercontent.com/41944640/133040792-548ab708-68c3-4a14-b6b2-8787ef02f7f5.png)

**Comment by luolovehk** [comment]
图片要点开博文才能显示完整，我的想法是直接把图文完整下载下来发到企业微信。

**Comment by nfe-w** [comment]
了解了，不过因为我这边暂时不太需要这个功能，所以暂时没有添加的计划，可以参考以下步骤进行修改

修改 https://github.com/nfe-w/weibo_dynamic_push/blob/master/push.py#L33 这个方法
判断参数`pic_url`参数不为空时，按照如下文档，将图片保存至企业微信并推送
[企业微信-上传临时素材](https://work.weixin.qq.com/api/doc/90000/90135/90253)
[企业微信-推送图片消息](https://work.weixin.qq.com/api/doc/90000/90135/90236#图片消息)

**Comment by luolovehk** [comment]
好的，感谢解答
