### ISSUE TITLE
大佬，2月28号开始失效了，希望修复一下！~

### ISSUE THREAD

**Issue by luolovehk** [nfe-w/weibo_dynamic_push#5]
已经检测不到内容了。

**Comment by nfe-w** [comment]
我这边是正常的😲
![iShot_2023-03-02_10 25 29](https://user-images.githubusercontent.com/41944640/222314912-c7af5f91-7df5-4df1-b65f-b2705ebbe390.png)

**Comment by luolovehk** [comment]
![image](https://user-images.githubusercontent.com/61071476/222315539-3353b209-bd20-4b05-9f51-cc39c97f4742.png)
![image](https://user-images.githubusercontent.com/61071476/222315576-c2efaec4-c0ea-42da-ad09-0b59de71c829.png)

在家里跑的和在服务器通知跑的，都是获取不到。天气预报微博是有更新的。很奇怪

**Comment by nfe-w** [comment]
我试了下是有数据的，会不会是你查询的频率太高了，导致ip触发了风控

![iShot_2023-03-02_10 36 32](https://user-images.githubusercontent.com/41944640/222316567-78fbe215-13d0-46ad-88e5-9296749d292d.png)

**Comment by luolovehk** [comment]
都是3分钟每次的，跑了一年多了。家里才跑了3个月。

**Comment by nfe-w** [comment]
可以试试看这个链接是否有数据返回：https://m.weibo.cn/api/container/getIndex?type=uid&value=2301257670&containerid=1076032301257670&count=25

**Comment by luolovehk** [comment]
![image](https://user-images.githubusercontent.com/61071476/222318206-6e23a504-066a-4f47-9f82-07a380adb291.png)

有数据返回的，之前用自己的微博测试也是能获取并推送的，长时间挂着，就获取不到这个天气。
我现在只跑一个用户了。看看有更新会怎样。

**Comment by nfe-w** [comment]
👌🏻

**Comment by luolovehk** [comment]
![image](https://user-images.githubusercontent.com/61071476/222385958-562ca460-fbe7-4a7a-8dd1-afbbf6f37f57.png)
![image](https://user-images.githubusercontent.com/61071476/222386216-bcede962-b3c8-4bd6-a8b5-75145f730421.png)
![image](https://user-images.githubusercontent.com/61071476/222386598-525f1b96-cf9a-43f4-ae49-e6615eac7a93.png)

帮忙看一下是什么原因，七海Nana7mi这个是可以推送的，唯独这个微博不行，是因为#关键字。还是置顶了转发微博的原因。

**Comment by nfe-w** [comment]
你最后一次拉这个代码是什么时间呢，我在22年7月 ec006e2ee64d5eb8a827ab5d98fd281e03addf6d 修复过置顶的bug，可以拉最新代码试一下

**Comment by luolovehk** [comment]
> 你最后一次拉这个代码是什么时间呢，我在22年7月 [ec006e2](https://github.com/nfe-w/weibo_dynamic_push/commit/ec006e2ee64d5eb8a827ab5d98fd281e03addf6d) 修复过置顶的bug，可以拉最新代码试一下

好的，谢谢！

**Comment by luolovehk** [comment]
新库问题已经得到解决，谢谢
